Compiled with bison 2.4.2

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,7 +1,14 @@
 #!/bin/bash
-clear
-rm sc
-rm sc.tab.c
+
+rm -f sc sc.tab.c
+
 bison sc.y
-gcc -o sc -O3 -lm -Wall sc.tab.c matrix.c reverse_polish.c stack.c symbol_table.c codegen.c functions.c variables.c
+
+if [ $? == 0 ]
+then
+	gcc -o sc -O3 -lm -Wall sc.tab.c matrix.c reverse_polish.c stack.c symbol_table.c codegen.c functions.c variables.c
+else
+	echo "Errors ocurred while running bison on sc.y.. Exiting."
+	exit 1
+fi
 
